### ISSUE TITLE
Do you have the data points you used for each of the experimental results table to release for reproducibility?

### ISSUE THREAD

**Issue by yrf1** [cultural-csk/candle#1]
For example, 
- Which set of commonsense descriptions did you compare for PLA, COM, DIS
- What are the set of trivia questions you asked in the extrinsic evaluation

I've download candle_dataset_v1.jsonl.zip but I don't see the specific experimental data samples there.

**Comment by phongnt570** [comment]
Hello. Thanks for your interest, and sorry for the late reply.

You can download the cultural questions here: https://www.mpi-inf.mpg.de/fileadmin/inf/d5/research/candle/500-cultural-multiple-choice-questions.jsonl

For the intrinsic evaluation (i.e., the PLA, COM, DIS metrics), we randomly sampled assertions from all compared resources.
